# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [6]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt

### 2. Install/Upgrade another package (e.g. Pandas) 

In [8]:
import pandas as pd

### 3. Import NumPy as <i> np </i>

In [10]:
import numpy as np

### 4.1 Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [113]:
array_hw_1 = np.array([4,5,7,10])

### 4.2 Use the<i> np.array() </i>function to create an array variable - <i>array_hw_2</i> with the numbers 10,3,7 and 2 in it

In [77]:
array_hw_2 = np.array([10,3,7,2])

### 5. Display arrays on screen

In [115]:
array_hw_1

array([ 4,  5,  7, 10])

In [117]:
array_hw_2

array([10,  3,  7,  2])

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and array_hw_2 and display it on the screen

In [119]:
# Per risolvere questo problema dobbiamo in primis convertire i nostri numpy array in liste

array_hw_1_list = array_hw_1.tolist()
array_hw_2_list = array_hw_2.tolist()


In [121]:
array_hw_1_list

[4, 5, 7, 10]

In [109]:
array_hw_2_list

[10, 3, 7, 2]

In [123]:
array_hw_M = np.array([array_hw_1_list,array_hw_2_list])

In [125]:
array_hw_M

array([[ 4,  5,  7, 10],
       [10,  3,  7,  2]])

### 7. Call the <i> np.mean() </i> function on each array

In [134]:
# La funzione np.mean calcola la media totale per riga di tutta la matrice. Nel nostro esempio, si effettua 
# per prima cosa la somma della prima riga (4+5+7+10 = 26), e dopo si effettua la somma della seconda riga
# (10+3+7+2 = 22). Infine, si sommano i risultati ottenuti e si dividono per il numero totale di elementi nella nostra 
# matrice. Quindi si ha ((26+22)/8 = 6).

array_hw_M_media_totale_riga = np.mean(array_hw_M)


In [136]:
array_hw_M_media_totale_riga

6.0

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_M</i>

In [148]:
# Calcoliamo ora le medie parziali per riga. La media parziale della prima riga sarà ((4+5+7+10)/2= 6.5),
# mentre la riga parziale della seconda riga sarà ((10+3+7+2)/4 = 5.5).
# Per farlo in python, si aggiunge il parametro axis nella funzione np.mean(). La formula sarà la seguente:

array_hw_M_medie_parziali_riga = np.mean(array_hw_M, axis=1)

In [150]:
array_hw_M_medie_parziali_riga

array([6.5, 5.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_M</i>

In [152]:

# La situazione è la stessa della precedente, ma si calcola la media parziale delle colonne. Avremo quindi che:

# ((4+10)/2=7)
# ((5+3)/2=4)
# ((7+7)/2=7)
# ((10+2)/2=6)


array_hw_M_medie_parziali_colonna = np.mean(array_hw_M, axis=0)

In [154]:
array_hw_M_medie_parziali_colonna

array([7., 4., 7., 6.])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

In [ ]:
np.mean()

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 