Nella lezione precedente abbiamo creato degli array a partire da liste python base. Ci sono altri modi.

1. np.ones((rows,columns),dtype) ==> In questo modo si genera un array i cui elementi sono tutti pari a 1. Se il parametro dtype non viene specificato, questi valori sono espressi con tipo float
2. np.zeros((rows,columns),dtype) ==> Stessa cosa di prima, ma invece di creare un array di 1 crea un array di 0.
3. np.arange(start,stop,step) ==> Crea un array UNDIMENSIONALE di interi, il cui primo elemento è pari a start e l'ultimo è pari a stop. il parametro step ci indica di quanto si salta da start a stop. Gli esempi che seguiranno chiariranno il tutto. Come al solito, il valore stop non è incluso
4. np.linspace(start,stop,step) ==>  stessa cosa di prima, ma invece di creare un range di interi crea un range di float
5. np.array.reshape(rows,cols) ==> Crea un array nelle dimensioni specificate. Anche questo sarà più chiaro con gli esempi sottostanti

In [4]:
import numpy as np

np.ones((rows,columns),dtype)

In [6]:
# Si ricorda che la funzione np.ones genera una matrice di zeri. Le righe di questa matrice sono rows, le colonne sono columns.
# In questo primo esempio NON specificheremo il dtype

M = np.ones((6,5))

In [7]:
M

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Poichè il dtype non è stato assegnato, abbiamo ottenuto una matrice i cui valori 1 sono float. Per renderli
# integer, si avrà che dtype= int

M2 = np.ones((6,5),int)

In [9]:
M2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# Se vogliamo avere un array unidimensionale (Matrice composta da una sola colonna o vettore colonna) si 
# dichiara solo il numero delle righe

M3 = np.ones((5,))

In [11]:
M3

array([1., 1., 1., 1., 1.])

In [12]:
M3 = np.ones(5,)

In [114]:
M3

array([1., 1., 1., 1., 1.])

In [13]:
# Se vogliamo avere un array unidimensionale ma colonna, ossia una matriche con una matrice con una riga sola
# e k colonne, oppure un vettore riga, possoamo trasporre M3

In [14]:
M3.T

array([1., 1., 1., 1., 1.])

In [15]:
# Oppure
M3.T

array([1., 1., 1., 1., 1.])

In [16]:
# NON possiamo invece utilizzare la seguente notazione

# M3 = np.ones((,5))


Gli esempi visti finora sono identici a quelli che vedremo con np.zeros((rows,columns),dtype)

In [18]:
M = np.zeros((6,5))

In [19]:
M

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
M2 = np.ones((6,5),int)

In [21]:
M2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
M3 = np.ones((5,))

In [23]:
M3

array([1., 1., 1., 1., 1.])

In [24]:
M3.T

array([1., 1., 1., 1., 1.])

Studiamo ora la funzione arange, la cui definizione si trova all'inizio della lezione. Si ricorda che la funzione
arange è definita nel seguente modo:

np.arange(start,stop,step)

In [26]:
# Nel primo caso NON definiremo il parametro step. Come si immagina, supponendo che start sia 3 ed end sia 10, 
# otterremo il seguente risultato

np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
# Come pronosticato, dato che l'estremo superiore 10 NON è incluso, il nostro array unidimensionale avrà 9 come ultimo elemento 

In [28]:
# Introduciamo ora il parametro step. Questo parametro ci dice che, partendo da 3, si arriva a 10 (escluso) per step.
# se step = 2, avremmo che la nostra sequenza sarà:  3 5 7 9

np.arange(3,10,2)

array([3, 5, 7, 9])

Con la funzione arange possiamo anche creare dei numpy array. per farlo, si estende la nostra funzione:
np.arange().reshape(n,p),
dove n è il numero di array e p è il  numero di elementi di ciascun array.


Vediamo un esempio

In [30]:
np.arange(4,12,2).reshape(2,2)

array([[ 4,  6],
       [ 8, 10]])

In [119]:
np.arange(4,33,2).reshape(5,3)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32]])

La fuzione linspace funziona in modo diverso alla funzione arange, Intanto crea elementi di tipo float,
np.linspace(start,stop,step)

In [32]:
np.linspace(8,20)

array([ 8.        ,  8.24489796,  8.48979592,  8.73469388,  8.97959184,
        9.2244898 ,  9.46938776,  9.71428571,  9.95918367, 10.20408163,
       10.44897959, 10.69387755, 10.93877551, 11.18367347, 11.42857143,
       11.67346939, 11.91836735, 12.16326531, 12.40816327, 12.65306122,
       12.89795918, 13.14285714, 13.3877551 , 13.63265306, 13.87755102,
       14.12244898, 14.36734694, 14.6122449 , 14.85714286, 15.10204082,
       15.34693878, 15.59183673, 15.83673469, 16.08163265, 16.32653061,
       16.57142857, 16.81632653, 17.06122449, 17.30612245, 17.55102041,
       17.79591837, 18.04081633, 18.28571429, 18.53061224, 18.7755102 ,
       19.02040816, 19.26530612, 19.51020408, 19.75510204, 20.        ])

In [33]:
# Che cavolo è successo?? Boh. Sembra che sia obbligatorio definire il parametro step per avere un risultato decente

In [34]:
# Ancora non ha senso. Proviamo con step > 1

In [35]:
np.linspace(8,20,4)

array([ 8., 12., 16., 20.])

In [36]:
np.linspace(8,20,3)

array([ 8., 14., 20.])

In [37]:
np.linspace(3,20,7)

array([ 3.        ,  5.83333333,  8.66666667, 11.5       , 14.33333333,
       17.16666667, 20.        ])

Quindi, il codice inserito ci dice che, partendo da 1, si arriva al numero 20 tramite 7 passaggi. 
Ma come calcoliamo la ragione? Si consideri il seguente teorema.

Sia inf l'estermo inferiore (nel nostro esempio 3), e sia sup l'estremo superiore (nel nostro caso 20).
Sia p la quantità di numeri necessaria per raggiungere l'estremo superiore (nel nostro caso 7).

La ragione sarà: (sup - inf) / (p - 1).

Nel nostro esempio: (20 - 3) / (7 -1)

==> 17 / 6 
==> 2.83333

Vediamo quindi se è vero



In [39]:
3 + 2.83333

5.83333

In [40]:
5.83333 + 2.83333

8.66666

In [41]:
8.66666 + 2.83333

11.49999

In [42]:
11.49999 + 2.83333

14.33332

In [43]:
14.33332 + 2.83333

17.16665

In [44]:
17.16665 + 2.83333

19.99998

In [45]:
# PERFETTO! Si noti che, a differenza della funzione np.arange, nella funzione np.linspace l'estremo superiore è incluso.

In [133]:
# MATRICE IDENTITA. LA MATRICE IDENTITA è UGUALE ALLA SUA TRASPOSTA

In [125]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [131]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])